-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Order"
(
    order_id serial NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    order_time timestamp without time zone NOT NULL,
    CONSTRAINT "Order_pkey" PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.ordering
(
    ordering_id serial NOT NULL,
    client_id integer NOT NULL,
    courier_id integer NOT NULL,
    order_id integer NOT NULL,
    CONSTRAINT ordering_pkey PRIMARY KEY (ordering_id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    client_id serial NOT NULL,
    client_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT client_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.courier
(
    courier_id serial NOT NULL,
    courier_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    transport character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT courier_pkey PRIMARY KEY (courier_id)
);

CREATE TABLE IF NOT EXISTS public."Dish"
(
    "Dish_ID" integer NOT NULL,
    total_amount integer NOT NULL,
    dish_price integer NOT NULL,
    PRIMARY KEY ("Dish_ID")
);

ALTER TABLE IF EXISTS public.ordering
    ADD CONSTRAINT fk_ordering_client FOREIGN KEY (client_id)
    REFERENCES public.client (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ordering
    ADD CONSTRAINT fk_ordering_courier FOREIGN KEY (courier_id)
    REFERENCES public.courier (courier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ordering
    ADD CONSTRAINT fk_ordering_order FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Dish"
    ADD FOREIGN KEY ("Dish_ID")
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;